name: Fixture Tests

on:
  push:
    branches:
      - main
      - master
  pull_request: {}

concurrency:
  group: fixture-tests-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{matrix.os}}
    timeout-minutes: 10
    strategy:
      matrix:
        os: ['windows-latest', 'ubuntu-latest']

    steps:
      - uses: wyvox/action@v1
      - run: pnpm test:fixture

